"""time_created, time_added columns

Revision ID: 5a1097c9e6eb
Revises: 
Create Date: 2020-11-04 20:33:08.569991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a1097c9e6eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendars',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('google_id', sa.String(
                        length=100), nullable=False),
                    sa.Column('webhook_channel', sa.String(
                        length=100), nullable=True),
                    sa.Column('webhook_created_at',
                              sa.DateTime(), nullable=True),
                    sa.Column('time_created', sa.DateTime(), nullable=True),
                    sa.Column('time_updated', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('google_id'),
                    sa.UniqueConstraint('webhook_channel')
                    )
    op.create_table('events',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('google_id', sa.String(
                        length=100), nullable=False),
                    sa.Column('open_at', sa.DateTime(), nullable=False),
                    sa.Column('created', sa.Boolean(),
                              server_default=sa.text('0'), nullable=False),
                    sa.Column('opened', sa.Boolean(),
                              server_default=sa.text('0'), nullable=False),
                    sa.Column('calendar_id', sa.Integer(), nullable=False),
                    sa.Column('time_created', sa.DateTime(), nullable=True),
                    sa.Column('time_updated', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['calendar_id'], ['calendars.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('google_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('calendars')
    # ### end Alembic commands ###
